- name: Update the apt package index
  apt:
    update_cache: yes
  become: true

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: true

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Set up the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes
  become: true

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: latest
  become: true

- name: Add ssh user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
