---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gas-oracle-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  rollup-config.json: |
{{ .Values.scrollConfig | indent 4 }}
