---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chain-monitor-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  chain-monitor-config.json: |
{{ .Values.scrollConfig | indent 4 }}
