{
 "title": "bridge-history-fetcher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Sync status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L1 message fetcher running total",
   "type": "timeseries",
   "description": "Current count of running L1 message fetcher instances.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "L1_message_fetcher_running_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L1 message fetcher reorg total",
   "type": "timeseries",
   "description": "Total count of blockchain reorgs encountered by the L1 message fetcher.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "L1_message_fetcher_reorg_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L1_message_fetcher_sync_height",
   "type": "timeseries",
   "description": "Latest blockchain height the L1 message fetcher has synced with.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "L1_message_fetcher_sync_height{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L2 message fetcher running total",
   "type": "timeseries",
   "description": "Current count of running L2 message fetcher instances.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "L2_message_fetcher_running_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L2 message fetcher reorg total",
   "type": "timeseries",
   "description": "Total count of blockchain reorgs encountered by the L2 message fetcher.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "L2_message_fetcher_reorg_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L2_message_fetcher_sync_height",
   "type": "timeseries",
   "description": "Latest blockchain height the L2 message fetcher has synced with.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "L2_message_fetcher_sync_height{instance=\"${instance:pipe}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "L1 fetcher logic fetched total",
   "type": "timeseries",
   "description": "The total number of events or failed txs fetched in L1 fetcher logic.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "L1_fetcher_logic_fetched_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L2 fetcher logic fetched total",
   "type": "timeseries",
   "description": "The total number of events or failed txs fetched in L2 fetcher logic.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "L2_fetcher_logic_fetched_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}