{
 "title": "chain-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Check status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L1 chain block number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "contract_controller_block_number{instance=\"${instance:pipe}\", layer=\"Layer1\"}",
     "legendFormat": "block_numer-{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L2 chain block number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "contract_controller_block_number{instance=\"${instance:pipe}\", layer=\"Layer2\"}",
     "legendFormat": "block_numer-{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L1 controller running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "contract_controller_running_total{instance=\"${instance:pipe}\", layer=\"Layer1\"}",
     "legendFormat": "running-{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L2 controller running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "contract_controller_running_total{instance=\"${instance:pipe}\", layer=\"Layer2\"}",
     "legendFormat": "running-{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L1 cross chain Gateway checked total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "cross_chain_checked_gateway_event_check_total{instance=\"${instance:pipe}\", layer=\"Layer1\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L1 cross chain ETH checked total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "cross_chain_checked_eth_total{instance=\"${instance:pipe}\", layer=\"Layer1\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L1 cross chain running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "cross_chain_check_controller_running_total{instance=\"${instance:pipe}\", layer=\"Layer1\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L2 cross chain Gateway checked total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "cross_chain_checked_gateway_event_check_total{instance=\"${instance:pipe}\", layer=\"Layer2\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L2 cross chain ETH checked total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "cross_chain_checked_eth_total{instance=\"${instance:pipe}\", layer=\"Layer2\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "L2 cross chain running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "cross_chain_check_controller_running_total{instance=\"${instance:pipe}\", layer=\"Layer2\"}",
     "legendFormat": "{{instance}}-{{layer}}"
    }
   ]
  },
  {
   "title": "alert slak running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "alert_slack_running_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alert ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "L2 withdraw root not match",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(slack_alert_withdraw_root_not_match_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "withdraw_root_not_match-{{instance}}"
    }
   ]
  },
  {
   "title": "gateway ---> transfer not match ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "irate(slack_alert_gateway_transfer_not_match_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "gateway->transfer-not-match-{{instance}} "
    }
   ]
  },
  {
   "title": "cross chain gateway check not match ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "irate(slack_alert_cross_chain_gateway_event_not_match_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "cross-chain-gateway-not-match-{{instance}} "
    }
   ]
  },
  {
   "title": "cross chain eth event check not match ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "irate(slack_alert_cross_chain_eth_event_not_match_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "cross-chain-eth-not-match-{{instance}} "
    }
   ]
  },
  {
   "title": "cross chain eth balance not match ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "irate(slack_alert_cross_chain_eth_event_balance_not_match_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "cross-chain-eth-balance-not-match-{{instance}} "
    }
   ]
  },
  {
   "title": "gateway event duplicated total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "irate(slack_alert_gateway_event_duplicated_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "gateway-event-duplicated-{{instance}} "
    }
   ]
  },
  {
   "title": "messenger event duplicated total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "irate(slack_alert_messenger_event_duplicated_total{instance=\"${instance:pipe}\"}[$__rate_interval])",
     "legendFormat": "messenger-event-duplicated-{{instance}} "
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "batch_status call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(chain_monitor_uri_request_total{instance=\"${instance:pipe}\", uri=\"/v1/batch_status\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(chain_monitor_uri_request_total{instance=\"${instance:pipe}\", uri=\"/v1/batch_status\"}[$__rate_interval])) by (uri, code)"
    }
   ]
  },
  {
   "title": "batch_status query latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le)(irate(chain_monitor_request_duration_bucket{instance=\"${instance:pipe}\", uri=\"/v1/batch_status\"}[$__rate_interval])))",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "gateway batch finalized call failed total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gateway_batch_finalized_failed_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "messenger batch finalized call failed total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "messenger_batch_finalized_failed_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  { "title": "Check failed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "filter gateway iterator failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "contract_controller_filter_gateway_iterator_failure_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "filter gateway iterator failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "contract_controller_filter_gateway_iterator_failure_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gateway check failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "contract_controller_gateway_check_failure_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "update or insert event failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "contract_controller_update_or_insert_failure_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "check withdraw root failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "contract_controller_check_l2_withdraw_root_failure_total{instance=\"${instance:pipe}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}