{
 "title": "bridge-history-v2-api",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "API QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "/api/txs QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txs\"}[$__rate_interval]))",
     "legendFormat": "bridge-history-all-qps"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txs\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txs\"}[$__rate_interval])) by (uri, code, instance)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/api/l2/withdrawals QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/withdrawals\"}[$__rate_interval]))",
     "legendFormat": "bridge-history-all-qps"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/withdrawals\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/withdrawals\"}[$__rate_interval])) by (uri, code, instance)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/api/l2/unclaimed/withdrawals QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/unclaimed/withdrawals\"}[$__rate_interval]))",
     "legendFormat": "bridge-history-all-qps"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/unclaimed/withdrawals\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(irate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/l2/unclaimed/withdrawals\"}[$__rate_interval])) by (uri, code, instance)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/api/txsbyhashes QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txsbyhashes\"}[$__rate_interval]))",
     "legendFormat": "bridge-history-all-qps"
    },
    {
     "expr": "sum(rate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txsbyhashes\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(bridge_history_api_uri_request_total{instance=~\"${instance:pipe}\", uri=\"/api/txsbyhashes\"}[$__rate_interval])) by (uri, code, instance)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "GetTxsByAddress cache hit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"}) /sum((bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetTxsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "bridge_history-all"
    },
    {
     "expr": "sum by (instance) (bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"}/(bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetTxsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "GetL2WithdrawalsByAddress cache hit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(bridge_history_api_cache_hits_total{api=\"GetL2WithdrawalsByAddress\", instance=~\"${instance:pipe}\"}) /sum((bridge_history_api_cache_hits_total{api=\"GetL2WithdrawalsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetL2WithdrawalsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "bridge_history-all"
    },
    {
     "expr": "sum by (instance) (bridge_history_api_cache_hits_total{api=\"GetL2WithdrawalsByAddress\", instance=~\"${instance:pipe}\"}/(bridge_history_api_cache_hits_total{api=\"GetL2WithdrawalsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetL2WithdrawalsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "GetTxsByAddress cache hit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(bridge_history_api_cache_hits_total{api=\"GetL2UnclaimedWithdrawalsByAddress\", instance=~\"${instance:pipe}\"}) /sum((bridge_history_api_cache_hits_total{api=\"GetL2UnclaimedWithdrawalsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetL2UnclaimedWithdrawalsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "bridge_history-all"
    },
    {
     "expr": "sum by (instance) (bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"}/(bridge_history_api_cache_hits_total{api=\"GetTxsByAddress\", instance=~\"${instance:pipe}\"} + bridge_history_api_cache_misses_total{api=\"GetTxsByAddress\",  instance=~\"${instance:pipe}\"}))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "PostQueryTxsByHashes  hit cache (by single tx hash)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(bridge_history_api_cache_hits_total{api=\"PostQueryTxsByHashes\", instance=~\"${instance:pipe}\"}) / sum((bridge_history_api_cache_misses_total{api=\"PostQueryTxsByHashes\", instance=~\"${instance:pipe}\"} +bridge_history_api_cache_hits_total{api=\"PostQueryTxsByHashes\", instance=~\"${instance:pipe}\"}))",
     "legendFormat": "bridge-history-all-cache-hits"
    },
    {
     "expr": "sum(bridge_history_api_cache_hits_total{api=\"PostQueryTxsByHash\", instance=~\"${instance:pipe}\"} / (bridge_history_api_cache_misses_total{api=\"PostQueryTxsByHash\", instance=~\"${instance:pipe}\"} +bridge_history_api_cache_hits_total{api=\"PostQueryTxsByHash\", instance=~\"${instance:pipe}\"})) by (instance)",
     "legendFormat": "{{instance}}-cache-hits"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "/api/txs Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/txs\"}[$__rate_interval])))",
     "legendFormat": "bridge-history-all"
    },
    {
     "expr": "histogram_quantile(${P99}, sum by (le, instance)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/txs\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/api/l2/withdrawals Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/l2/withdrawals\"}[$__rate_interval])))",
     "legendFormat": "bridge-history-all"
    },
    {
     "expr": "histogram_quantile(${P99}, sum by (le, instance)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/l2/withdrawals\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/api/l2/unclaimed/withdrawals Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/l2/unclaimed/withdrawals\"}[$__rate_interval])))",
     "legendFormat": "bridge-history-all"
    },
    {
     "expr": "histogram_quantile(${P99}, sum by (le, instance)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/l2/unclaimed/withdrawals\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/api/txsbyhashes Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/txsbyhashes\"}[$__rate_interval])))",
     "legendFormat": "bridge-hisotry-all"
    },
    {
     "expr": "histogram_quantile(${P99}, sum by (le, instance)(irate(bridge_history_api_request_duration_bucket{instance=~\"${instance:pipe}\", uri=\"/api/txsbyhashes\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}