repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts/
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
            args: [--allow-multiple-documents]
            exclude: ".*templates.*"
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
