---
global:
  nameOverride: &app_name balance-checker
  fullnameOverride: *app_name

image:
  repository: scrolltech/balance-checker
  pullPolicy: Always
  tag: 0.0.2

env:
  - name: BIND_PORT
    value: "8080"
  - name: METRICS_PORT
    value: "8090"
  - name: METRICS_URL
    value: 0.0.0.0
  - name: SLACK_NOTIFY_URL
    value: ""

initContainers:
  1-wait-for-l1:
    image: scrolltech/scroll-alpine:v0.0.1
    command:
      - /bin/sh
      - -c
      - /wait-for-l1.sh $SCROLL_L1_RPC
    envFrom:
      - configMapRef:
          name: balance-checker-env
    volumeMounts:
      - name: wait-for-l1-script
        mountPath: /wait-for-l1.sh
        subPath: wait-for-l1.sh
  2-wait-for-l2-rpc:
    image: atkrad/wait4x:latest
    args:
      - http
      - http://l2-rpc:8545
      - --expect-status-code
      - "200"
      - --timeout
      - "0"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: true
    type: configMap
    mountPath: /app/config/
    name: balance-checker-config
  env:
    enabled: true
    type: configMap
    mountPath: /config/
    name: balance-checker-env
  wait-for-l1-script:
    enabled: true
    type: configMap
    name: wait-for-l1-script
    defaultMode: "0777"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 8090

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-sdk
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s

scrollConfig: |
  {}
