apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: 1-wait-for-postgres
        image: atkrad/wait4x:latest
        args:
          - tcp
          - postgresql:5432
          - --timeout
          - "0"
      containers:
        - name: init-db-and-get-batch-info
          image: postgres:latest
            - configMapRef:
                name: l1-devnet-env
            - configMapRef:
                name: rollup-node-env
            - configMapRef:
                name: balance-checker-env
          env:
            - name: PG_HOST
              value: {{ .Values.db.pg_host }}
            - name: POSTGRES_DB
              value: scroll
            - name: PG_USER
              value: {{ .Values.db.pg_user }}
            - name: PG_PORT
              value: {{ .Values.db.pg_port | quote }}
            - name: DB_USER
              value: bridge_history
            - name: DB_PASSWORD
              value: {{ .Values.db.bridge_history_password }}
            - name: L1_MAINNET_SCROLL_CHAIN_PROXY_ADDR
              value: {{ .Values.l1.mainnet_scroll_chain_proxy_addr }}
            - name: L1_MAINNET_SCROLL_OWNER_ADDR
              value: {{ .Values.l1.mainnet_scroll_owner_addr }}
            - name: SCROLL_RDS_ROLLUP_NODE_DSN
              value: {{ .Values.db.scroll_rds_rollup_node_dsn }}
          command: ["/bin/bash", "-c", "./init-db.sh && ./wait-l1-and-get-batch-info.sh && ./modify-l1-scroll-chain-contract-whitelist.sh"]
          volumeMounts:
            - name: init-db
              mountPath: /init-db.sh
              subPath: init-db.sh
            - name: wait-l1-and-get-batch-info
              mountPath: /wait-l1-and-get-batch-info.sh
              subPath: wait-l1-and-get-batch-info.sh
            - name: modify-l1-scroll-chain-contract-whitelist
              mountPath: /modify-l1-scroll-chain-contract-whitelist.sh
              subPath: modify-l1-scroll-chain-contract-whitelist.sh
      restartPolicy: Never
      volumes:
        - name: init-db
          configMap:
            name: init-db
            defaultMode: 0777
        - name: wait-l1-and-get-batch-info
          configMap:
            name: wait-l1-and-get-batch-info
            defaultMode: 0777
        - name: modify-l1-scroll-chain-contract-whitelist
          configMap:
            name: modify-l1-scroll-chain-contract-whitelist
            defaultMode: 0777
  backoffLimit: 4
