---
global:
  isStandalone: false

image:
  repository: scrolltech/scroll-stack-contracts
  tag: deploy-64934888f4cd002e77414a8e62812f70c00c5937

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
