apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-contracts-deployment
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: contracts-deployment
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
          {{- range $env := .Values.env }}
            - name: {{ $env.name }}
              value: {{ $env.value }}
          {{- end }}
          volumeMounts:
            - mountPath: /contracts/volume
              name: config
      restartPolicy: Never
      initContainers:
        - name: wait-for-other-pod
          image: curlimages/curl
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "l2-sequencer:8545" -o /dev/null) -ne 200 ] && 
              [ $(curl -sw '%{http_code}' "l1-devnet:8545" -o /dev/null) -ne 404 ]; do
                sleep 5;
              done
      volumes:
        - configMap:
            name: scroll-smart-contracts-config
          name: config
  backoffLimit: 4
