apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-contracts-deployment
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: contracts-deployment
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
          {{- range $env := .Values.env }}
            - name: {{ $env.name }}
              value: {{ $env.value }}
          {{- end }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 10 }}
          volumeMounts:
            - mountPath: /contracts/volume
              name: config
      restartPolicy: Never
      initContainers:
        - name: 1-wait-for-l1-devnet
          image: atkrad/wait4x:latest
          args:
            - http
            - $(L1_RPC_ENDPOINT)
            - --expect-status-code
            - "400"
          envFrom:
            - configMapRef:
                name: contracts-env
        - name: 2-wait-for-l2-sequencer
          image: atkrad/wait4x:latest
          args:
            - http
            - $(L2_RPC_ENDPOINT)
            - --expect-status-code
            - "200"
            - --timeout
            - "0"
          envFrom:
            - configMapRef:
                name: contracts-env

      volumes:
        - configMap:
            name: scroll-smart-contracts-config
          name: config
  backoffLimit: 4
