---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scroll-smart-contracts-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  config.toml: |
{{ .Values.scrollConfig | indent 4 }}
  config-contracts.toml: |
{{ .Values.scrollConfigContracts | indent 4 }}
