global:
  isStandalone: true

initContainers:
  1-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(DATABASE_URL)
      - --timeout
      - "0"
    envFrom:
      - secretRef:
          name: chain-monitor-secret-env
  4-wait-for-l2-sequencer:
    image: atkrad/wait4x:latest
    args:
      - http
      - $(SCROLL_L2_RPC)
      - --expect-status-code
      - "200"
      - --timeout
      - "0"
    envFrom:
      - configMapRef:
          name: chain-monitor-env

configMaps:
  env:
    enabled: true
    data:
      SCROLL_L1_RPC: ""
      SCROLL_L2_RPC: ""

externalSecrets:
  chain-monitor-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/chain-monitor-secret-env
          property: DATABASE_URL
        secretKey: DATABASE_URL
    refreshInterval: 2m
    serviceAccount: external-secrets
