---
global:
  nameOverride: &app_name l1-devnet
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: Recreate
  type: deployment

image:
  repository: ghcr.io/foundry-rs/foundry
  pullPolicy: Always
  tag: nightly-19d69f277de96f621d930cdb767a9693c55ae8e1

command:
  ["/bin/sh","-c","source /chain-id/chain-id.txt && anvil --host 0.0.0.0 --port 8545 --chain-id ${CHAIN_ID}"]

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

initContainers:
  get-chain-id:
    image: busybox
    env:
      - name: DATABASE_URL
        value: "postgresql://postgres:qwerty12345@postgresql:5432/blockscout"
    command: ["/bin/sh", "-c"]
    args:
      - >
        CHAIN_ID=$(grep 'CHAIN_ID_L1' /config/config.toml | awk -F'=' '{print $2}' | tr -d ' "') && 
        echo "CHAIN_ID=\"${CHAIN_ID}\"" > /chain-id/chain-id.txt && cat /chain-id/chain-id.txt;
    volumeMounts:
      - name: config-toml
        mountPath: /config
      - name: chain-id
        mountPath: /chain-id

persistence:
  config-toml:
    enabled: yes
    type: configMap
    mountPath: /config
    name: scroll-smart-contracts-config
  chain-id:
    enabled: yes
    type: pvc
    accessMode: ReadWriteOnce
    size: 10Mi
    mounthPath: /chain-id

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8545
        targetPort: 8545

defaultProbes: &default_probes
  enabled: false
  tcpSocket:
    port: 8545

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes