envFrom:
  - secretRef:
      name: blockscout-secret-env

persistence:
  env:
    enabled: true
    type: secret
    mountPath: /config/
    name: blockscout-secret-env

initContainers:
  1-migrate-db:
    image: blockscout/blockscout:6.6.0
    command: ["/bin/sh", "-c", "/app/bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\""]
    envFrom:
      - secretRef:
          name: blockscout-secret-env

configMaps:
  env:
    enabled: true
    data:
      PG_HOST: "postgresql-blockscout"
      PG_PORT: "5432"

ingress:
  main:
    ingressClassName: "nginx"
    hosts:
      - host: blockscout.scrollsdk
        paths:
          - path: /
            pathType: Prefix

externalSecrets:
  blockscout-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/blockscout-secret-env
          property: DATABASE_URL
        secretKey: DATABASE_URL
    refreshInterval: 2m
    serviceAccount: external-secrets
