blockscout-stack:
  blockscout:

    env:
      ETHEREUM_JSONRPC_HTTP_URL: http://l2-rpc:8545
      ETHEREUM_JSONRPC_TRACE_URL: http://l2-rpc:8545
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_WS_URL: ws://l2-rpc:8546
      BLOCK_TRANSFORMER: clique
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      CHAIN_TYPE: scroll
      INDEXER_SCROLL_L1_RPC: ""
      INDEXER_SCROLL_L1_CHAIN_CONTRACT: ""  # value of L1_SCROLL_CHAIN_PROXY_ADDR on config-contracts.toml
      INDEXER_SCROLL_L1_BATCH_START_BLOCK: ""  # value of L1_CONTRACT_DEPLOYMENT_BLOCK on config.toml
      INDEXER_SCROLL_L1_MESSENGER_CONTRACT: ""  # value of L1_SCROLL_MESSENGER_PROXY_ADDR on config-contracts.toml
      INDEXER_SCROLL_L1_MESSENGER_START_BLOCK: ""  # value of L1_CONTRACT_DEPLOYMENT_BLOCK on config.toml
      INDEXER_SCROLL_L2_MESSENGER_CONTRACT: ""  # value of L2_SCROLL_MESSENGER_PROXY_ADDR on config-contracts.toml
      INDEXER_SCROLL_L2_GAS_ORACLE_CONTRACT: ""  # value of L1_GAS_PRICE_ORACLE_PROXY_ADDR on config-contracts.toml
      INDEXER_SCROLL_L2_MESSENGER_START_BLOCK: 0
      INDEXER_SCROLL_L1_ETH_GET_LOGS_RANGE_SIZE: 500
      INDEXER_SCROLL_L2_ETH_GET_LOGS_RANGE_SIZE: 500
      SCROLL_L2_CURIE_UPGRADE_BLOCK: 0

    envFrom:
      - secretRef:
          name: blockscout-secret-env

    ingress:
      enabled: true
      className: "nginx"
      annotations: {} # Add annotations here. Might be necessary to allow CORS from updated-gas-oracle. Example below
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        # nginx.ingress.kubernetes.io/enable-cors: "true"
        # nginx.ingress.kubernetes.io/cors-allow-origin: "https://blockscout.scrollsdk"
        # nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        # nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        # nginx.ingress.kubernetes.io/cors-max-age: "86400"
      hostname: "" # Set here the hostname for the ingress. Example : blockscout-backend.scrollsdk

  frontend:
    ingress:
      enabled: true
      ingressClassName: ""  # Set here your ingressClassName
      annotations: {}  # Add annotations here. Might be necessary to allow CORS from updated-gas-oracle. Example below
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        # nginx.ingress.kubernetes.io/enable-cors: "true"
        # nginx.ingress.kubernetes.io/cors-allow-origin: "https://blockscout.scrollsdk"
        # nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        # nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        # nginx.ingress.kubernetes.io/cors-max-age: "86400"
      hostname: "" # Set here the hostname for the ingress. Example : blockscout-backend.scrollsdk

externalSecrets:
  blockscout-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/blockscout-secret-env
          property: DATABASE_URL
        secretKey: DATABASE_URL
    refreshInterval: 2m
    serviceAccount: external-secrets
