---
global:
  nameOverride: &app_name l2-sequencer
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: statefulset

image:
  repository: scrolltech/l2geth
  pullPolicy: Always
  tag: scroll-v5.7.21

env:
  - name: L2GETH_L1_WATCHER_CONFIRMATIONS
    value: "0x6"
  - name: L2GETH_LOCALS
    value: ""
  - name: L2GETH_ENABLE_CCC
    value: "true"
  - name: L2GETH_MINER_GASLIMIT
    value: "10000000"
  - name: L2GETH_RPC_HTTP_PORT
    value: &http_port 8545
  - name: L2GETH_RPC_WS_PORT
    value: &ws_port 8546
  - name: L2GETH_P2P_PORT
    value: "30303"
  - name: L2GETH_MIN_GAS_PRICE
    value: "1000000"
  - name: VERBOSITY
    value: "3"
  - name: L2_SHADOWFORK_BLOCK_NUMBER
    value: "0xe9a5"

envFrom:
  - configMapRef:
      name: l2-sequencer-env

command:
  [
    "bash",
    "-c",
    "(until geth attach http://localhost:$L2GETH_RPC_HTTP_PORT --exec \"eth.blockNumber\" > /dev/null 2>&1; do \
      echo \"Waiting for RPC to become available...\"; \
      sleep 5; \
    done && \
    echo \"RPC is now available. Executing debug_setHead...\" && \
    geth attach http://localhost:$L2GETH_RPC_HTTP_PORT --exec \"debug.setHead('${L2_SHADOWFORK_BLOCK_NUMBER}')\" && \
    echo \"debug_setHead executed.\") & \
    mkdir -p /l2geth/data/keystore && \
    mkdir -p /l2geth/data/geth && \
    cp -r /host/snapshot/* /l2geth/data/ && \
    echo ${L2GETH_PASSWORD} > /l2geth/password && \
    echo ${L2GETH_KEYSTORE}  > /l2geth/data/keystore/keystore.json && \
    echo ${L2GETH_NODEKEY} > /l2geth/data/geth/nodekey && \
    geth --datadir \"/l2geth/data\" init /l2geth/genesis/genesis.json && \
    geth --datadir \"/l2geth/data\" \
    --port \"$L2GETH_P2P_PORT\" --nodiscover --syncmode full --networkid \"$CHAIN_ID\" \
    --http --http.port \"$L2GETH_RPC_HTTP_PORT\" --http.addr \"0.0.0.0\" --http.vhosts=\"*\" --http.corsdomain \"*\" --http.api \"eth,scroll,net,web3,debug\" \
    --pprof --pprof.addr \"0.0.0.0\" --pprof.port 6060 \
    --ws --ws.port \"$L2GETH_RPC_WS_PORT\" --ws.addr \"0.0.0.0\" --ws.api \"eth,scroll,net,web3,debug\" \
    --net.shadowforkpeers empty \
    --unlock \"$L2GETH_SIGNER_ADDRESS\" --password \"/l2geth/password\" --allow-insecure-unlock --mine \
    --ccc --ccc.numworkers 5 \
    --gcmode archive \
    --cache.noprefetch \
    --verbosity ${VERBOSITY} \
    --txpool.globalqueue 4096 --txpool.globalslots 40960 --txpool.pricelimit \"$L2GETH_MIN_GAS_PRICE\" $LOCALS_FLAG \
    --miner.gasprice \"$L2GETH_MIN_GAS_PRICE\" --miner.gaslimit \"$L2GETH_MINER_GASLIMIT\" --rpc.gascap 0 --gpo.ignoreprice \"$L2GETH_MIN_GAS_PRICE\" \
    --gpo.percentile 20 \
    --gpo.blocks 100 \
    --l1.endpoint \"$L2GETH_L1_ENDPOINT\" --l1.confirmations \"$L2GETH_L1_WATCHER_CONFIRMATIONS\" --l1.sync.startblock \"$L2GETH_L1_CONTRACT_DEPLOYMENT_BLOCK\" \
    --rollup.verify \
    --metrics --metrics.expensive \
    $L2GETH_EXTRA_PARAMS"
  ]

initContainers:
  wait-for-l1:
    image: scrolltech/scroll-alpine:v0.0.1
    command:
      - /bin/sh
      - -c
      - /wait-for-l1.sh $L2GETH_L1_ENDPOINT
    envFrom:
      - configMapRef:
          name: l2-sequencer-env
    volumeMounts:
      - name: wait-for-l1-script
        mountPath: /wait-for-l1.sh
        subPath: wait-for-l1.sh

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: *http_port
        targetPort: *http_port
      ws:
        enabled: true
        port: *ws_port
        targetPort: *ws_port
      p2p:
        enabled: true
        port: 30303
        targetPort: 30303
      metrics:
        enabled: true
        port: 6060
        targetPort: 6060

resources:
  requests:
    memory: "4Gi"
    cpu: "1"
  limits:
    memory: "8Gi"
    cpu: "2"

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 8545

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

persistence:
  data:
    enabled: true
    type: pvc
    mountPath: /l2geth/data/
    name: l2geth-data
    size: 10Gi
    accessMode: ReadWriteOnce
  env:
    enabled: true
    type: configMap
    name: l2-sequencer-env
  genesis:
    enabled: true
    type: configMap
    mountPath: /l2geth/genesis/genesis.json
    subPath: genesis.json
    name: genesis-config
  wait-for-l1-script:
    enabled: true
    type: configMap
    name: wait-for-l1-script
    defaultMode: "0777"
  snapshot:
    enabled: true
    type: hostPath
    hostPath: /var/scroll/l2geth/snapshot
    mountPath: /host/snapshot
    hostPathType: Directory

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-sdk
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s
        path: /debug/metrics/prometheus
