global:
  nameOverride: &app_name bridge-history-fetcher
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: deployment

image:
  repository: scrolltech/bridgehistoryapi-fetcher
  pullPolicy: Always
  tag: v4.4.7

command:
  [
    "/bin/sh",
    "-c",
    "bridgehistoryapi-fetcher --config /app/conf/bridge-history-config.json --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} --log.debug",
  ]

env:
  - name: METRICS_PORT
    value: "8090"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8080
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

persistence:
  bridge-history-fetcher:
    enabled: yes
    type: configMap
    mountPath: /app/conf/
    name: bridge-history-config
  init-db:
    enabled: yes
    type: configMap
    mountPath: /init-db.sh
    name: init-db
    defaultMode: "0777"
  migrate-db:
    enabled: yes
    type: configMap
    mountPath: /config/migrate-db.json
    name: bridge-history-fetcher-migrate-db
    defaultMode: "0777"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/health"
      port: 8090

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

initContainers:
  init-db:
    image: postgres:latest
    env:
      - name: POSTGRES_DB
        value: scroll
      - name: PG_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_USER
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PGPASSWORD
      - name: PG_HOST
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_HOST
      - name: PG_PORT
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_PORT
      - name: DB_USER
        value: bridge_history_user
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: BRIDGE_HISTORY_PASSWORD
    #    command: ["bash", "-c",
    #      "psql -h $POSTGRES_URL -U $POSTGRES_USER -p 5432 -c \"CREATE DATABASE ${POSTGRES_DB};\""]
    command: ["bash", "-c", "./init-db.sh"]
    volumeMounts:
      - name: init-db
        mountPath: /init-db.sh
        subPath: init-db.sh
  migrate-db:
    image: scrolltech/bridgehistoryapi-db-cli
    command: ["/bin/sh", "-c", "db_cli reset --config /config/migrate-db.json"]
    volumeMounts:
      - name: migrate-db
        mountPath: /config/migrate-db.json
        subPath: migrate-db.json

configMaps:
  config:
    enabled: true
    data:
  migrate-db:
    enabled: true
    data:
      migrate-db.json: |
        {
          "l1": {},
          "l2": {},
          "db": {
            "driver_name": "postgres",
            "maxOpenNum": 50,
            "maxIdleNume": 5,
            "dsn": "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable"
          }
        }

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s