---
global:
  nameOverride: &app_name rollup-node
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: Recreate
  type: deployment

image:
  repository: scrolltech/rollup-relayer
  pullPolicy: Always
  tag: v4.4.2

env:
  - name: METRICS_PORT
    value: 8090

command: [
  "/bin/sh",
  "-c",
  "rollup_relayer --config /app/conf/rollup-config.json \
    --genesis /app/genesis/genesis.json \
    --import-genesis \
    --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} \
    --log.debug --verbosity 3",
]

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "100m"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8090

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false


persistence:
  *app_name:
    enabled: yes
    type: configMap
    mountPath: /app/conf/
    name: rollup-node-config
  genesis:
    enabled: yes
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config
  init-db:
    enabled: yes
    type: configMap
    mountPath: /init-db.sh
    name: init-db
    defaultMode: "0777"
  migrate-db:
    enabled: yes
    type: configMap
    mountPath: /config/migrate-db.json
    name: rollup-node-migrate-db
    defaultMode: "0777"

initContainers:
  init-db:
    image: postgres:latest
    env:
      - name: POSTGRES_DB
        value: scroll
      - name: PG_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_USER
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PGPASSWORD
      - name: PG_HOST
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_HOST
      - name: PG_PORT
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_PORT
      - name: DB_USER
        value: rollup_relayer
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: ROLLUP_RELAYER_PASSWORD
    command: ["bash","-c","./init-db.sh"]
    volumeMounts:
      - name: init-db
        mountPath: /init-db.sh
        subPath: init-db.sh
  migrate-db:
    image: scrolltech/rollup-db-cli
    command: ["/bin/sh","-c","db_cli migrate --config /config/migrate-db.json"]
    volumeMounts:
      - name: migrate-db
        mountPath: /config/migrate-db.json
        subPath: migrate-db.json

# Need genesis file and config.json
configMaps:
  migrate-db:
    enabled: true
    data:
      migrate-db.json: |
        {
            "driver_name": "postgres",
            "dsn": "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable"
        }

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: http
        interval: 1m
        scrapeTimeout: 10s
