---
global:
  nameOverride: &app_name l2-sequencer
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: statefulset

image:
  repository: scrolltech/l2geth
  pullPolicy: Always
  tag: v5.2.1-arm64

env:
  - name: L2GETH_ROLE
    value: "sequencer"
  - name: CHAIN_ID
    value: "222222"
  - name: L2GETH_SIGNER_ADDRESS
    value: "0x756EA06BDEe36de11F22DCca45a31d8a178eF3c6"
  - name: L2GETH_KEYSTORE
    value: '{"address":"756ea06bdee36de11f22dcca45a31d8a178ef3c6","crypto":{"cipher":"aes-128-ctr","ciphertext":"8bfb4e48c6b172f1f5794d2874476ca62f8184507c0916dbd45fe77a0056114c","cipherparams":{"iv":"509eb70e7379a776e0779634b6668277"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"ef0f0334e5db7c12d76993e1e9627593fd0d7cd44444b689e792c86bc8a5d75f"},"mac":"d766cac11d0bd563316f5655ebf07550b6fce98ba0ca3c13acdc1b65f5f185ca"},"id":"4459ad67-f2ce-48b2-8940-c0582106a4c6","version":3}'
  - name: L2GETH_PASSWORD
    value: "scroll2022"
  - name: L2GETH_NODEKEY
    value: "2f59ff2fdee1c42a3d8c8980c313bc8d6c2557463f7bb92b0f0bc89a6d3cbf01"
  - name: L2GETH_L1_CONTRACT_DEPLOYMENT_BLOCK
    value: "0"
  - name: L2GETH_L1_ENDPOINT
    value: "http://l1-devnet:8545"
  - name: L2GETH_L1_WATCHER_CONFIRMATIONS
    value: "0x6"
  - name: L2GETH_P2P_PORT
    value: &p2p_port 30303
  - name: L2GETH_PPROF_PORT
    value: &pprof_port 6060
  - name: L2GETH_EXTRA_PARAMS
    value: "--ccc"

command: [
  "bash",
  "-c",
  "/script/l2geth-boot.sh"
]

initContainers:
  wait-for-other-pod:
    image: curlimages/curl
    args:
      - /bin/sh
      - -c
      - >
        set -x;
        while [ $(curl -sw '%{http_code}' "l1-devnet:8545/api" -o /dev/null) -ne 404 ]; do
          sleep 5;
        done

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: *p2p_port
        targetPort: *p2p_port
      metrics:
        enabled: true
        port: *pprof_port
        targetPort: *pprof_port

resources:
  requests:
    memory: "150Mi"
    cpu: "50m"
  limits:
    memory: "8Gi"
    cpu: "100m"

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: *pprof_port

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes

persistence:
  boot:
    enabled: yes
    type: configMap
    mountPath: /script/
    name: l2geth-boot
    defaultMode: 0777
  data:
    enabled: yes
    type: pvc
    mountPath: /l2geth/data/
    name: l2geth-data
    size: 10Gi
    accessMode: ReadWriteOnce
  l2-sequencer:
    enabled: yes
    type: configMap
    mountPath: /l2geth/conf/
    name: l2-sequencer-config
  genesis:
    enabled: yes
    type: configMap
    mountPath: /l2geth/genesis/genesis.json
    subPath: genesis.json
    name: genesis-config

configMaps:
  config:
    enabled: true
    data:
      config.toml: |
        [Node.P2P] StaticNodes = "[]"

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s
        path: /debug/metrics/prometheus