---
global:
  nameOverride: &app_name rollup-explorer-backend
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: Recreate
  type: deployment

image:
  repository: scrolltech/rollup-explorer-backend
  pullPolicy: Always
  tag: v0.0.12

env:
  BIND_PORT: 5001
  #TODO change this to read only user
  DB_URL: "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable"
  OPEN_API_ADDR: "/rollupscan"
  MAX_PER_PAGE: 500

command: [
  "/bin/sh",
  "-c",
  "sleep 3600",
]
#
#command: [
#  "/bin/sh",
#  "-c",
#  "mkdir /bin/config/ && cp /app/config/rollup-config.json /bin/config/config.json && rollup_relayer --config /app/conf/rollup-config.json \
#    --genesis /app/genesis/genesis.json \
#    --import-genesis \
#    --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} \
#    --log.debug --verbosity 3",
#]

resources:
  requests:
    memory: "50Mi"
    cpu: "10m"
  limits:
    memory: "200Mi"
    cpu: "50m"

service:
  main:
    labels:
      app: *app_name
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
        targetPort: 8080
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

#TODO
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  *app_name:
    enabled: yes
    type: configMap
    mountPath: /app/config/
    name: rollup-node-config

ingress:
  main:
    enabled: true
    primary: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: rollup-explorer-backend.scrollsdk
        paths:
          - path: /
            pathType: Prefix

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: http
        interval: 1m
        scrapeTimeout: 10s
