---
controller:
  replicas: 1
  strategy: RollingUpdate
  type: statefulset

global:
  nameOverride: &app_name coordinator-api
  fullnameOverride: *app_name

image:
  repository: scrolltech/coordinator-api
  pullPolicy: Always
  tag: v4.4.7

env:
  - name: HTTP_PORT
    value: 8080
  - name: METRICS_PORT
    value: 8090
  - name: RUST_LOG
    value: info
  - name: SCROLL_PROVER_ASSETS_DIR
    value: "/data/assets/"

command: [
  "/bin/sh",
  "-c",
  "coordinator_api --config /coordinator/conf/coordinator-config.json \
    --genesis /app/genesis/genesis.json \
    --http --http.addr '0.0.0.0' --http.port ${HTTP_PORT} \
    --metrics --metrics.addr '0.0.0.0' --metrics.port ${METRICS_PORT} \
    --log.debug"
]

resources:
  requests:
    memory: "20Gi"
    cpu: "50m"
  limits:
    memory: "21Gi"
    cpu: "200m"

persistence:
  *app_name:
    enabled: yes
    type: configMap
    mountPath: /coordinator/conf/
    name: coordinator-config
  download-params:
    enabled: yes
    type: configMap
    mountPath: /download-params.sh
    name: coordinator-api-download-params
    defaultMode: "0777"
  genesis:
    enabled: yes
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config

volumeClaimTemplates:
  - name: verifier
    accessMode: "ReadWriteOnce"
    size: "50Gi"
    storageClass: "gp2"
    mountPath: "/verifier"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090
    annotations:
      external-dns.alpha.kubernetes.io/hostname: scroll-stack-coordinator-api.devnet.scroll.tech
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    type: LoadBalancer

defaultProbes: &default_probes
  enabled: false
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 8090

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes

initContainers:
  parameter-download:
    image: ubuntu
    command: ["sh", "-c", "/download-params.sh "]
    env:
      - name: RELEASE_VERSION
        value: "v0.10.3"
    volumeMounts:
      - name: verifier
        mountPath: /data
      - name: download-params
        mountPath: /download-params.sh
        subPath: download-params.sh
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"


configMaps:
  download-params:
    enabled: true
    data:
      download-params.sh: |
        #!/bin/sh
        apt update
        apt install wget libdigest-sha-perl -y

        P_CHECKSUMS=$(wget -O- https://circuit-release.s3.us-west-2.amazonaws.com/setup/sha256sum)
        DOWNLOAD_RESULT=$?
        ERROR=$(echo "$P_CHECKSUMS" | grep "Error")

        if [ $DOWNLOAD_RESULT -ne 0 ] || [ "$ERROR" != "" ]; then
        echo "Failed to download params checksums"
        echo "$P_CHECKSUMS"
        exit 1
        fi

        R_CHECKSUMS=$(wget -O- https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/sha256sum)
        DOWNLOAD_RESULT=$?
        ERROR=$(echo "$R_CHECKSUMS" | grep "Error")

        if [ $DOWNLOAD_RESULT -ne 0 ] || [ "$ERROR" != "" ]; then
        echo "Failed to download release checksum"
        echo "$R_CHECKSUMS"
        exit 1
        fi

        PARAMS24_SHASUM=$(echo "$P_CHECKSUMS" | grep "params24" | cut -d " " -f 1)
        PARAMS26_SHASUM=$(echo "$P_CHECKSUMS" | grep "params26" | cut -d " " -f 1)
        CHUNK_VK_SHASUM=$(echo "$R_CHECKSUMS" | grep "chunk_vk.vkey" | cut -d " " -f 1)
        BATCH_VK_SHASUM=$(echo "$R_CHECKSUMS" | grep "agg_vk.vkey" | cut -d " " -f 1)
        VRFR_SHASUM=$(echo "$R_CHECKSUMS" | grep "evm_verifier.bin" | cut -d " " -f 1)
        CFG2_SHASUM=$(echo "$R_CHECKSUMS" | grep "layer2.config" | cut -d " " -f 1)
        CFG4_SHASUM=$(echo "$R_CHECKSUMS" | grep "layer4.config" | cut -d " " -f 1)

        check_shasum () {
        SHASUM=$(shasum -a 256 $1 | cut -d " " -f 1)
        if [ "$SHASUM" != "$2" ]; then
        echo "Shasum mismatch: expected=$2, actual=$SHASUM"
          return 1;
          else
          return 0;
          fi
        }
        # check existing file checksums
        if [ -f /data/params/params24 ]; then
        if ! check_shasum "/data/params/params24" "$PARAMS24_SHASUM"; then
        echo "Removing incorrect file /data/params/params24\n"
        rm /data/params/params24
        fi
        fi

        if [ -f /data/params/params26 ]; then
        if ! check_shasum "/data/params/params26" "$PARAMS26_SHASUM"; then
        echo "Removing incorrect file /data/params/params26\n"
        rm /data/params/params26
        fi
        fi

        if [ -f /data/assets/chunk_vk.vkey ]; then
        if ! check_shasum "/data/assets/chunk_vk.vkey" "$CHUNK_VK_SHASUM"; then
        echo "Removing incorrect file /data/assets/chunk_vk.vkey\n"
        rm /data/assets/chunk_vk.vkey
        fi
        fi

        if [ -f /data/assets/agg_vk.vkey ]; then
        if ! check_shasum "/data/assets/agg_vk.vkey" "$BATCH_VK_SHASUM"; then
        echo "Removing incorrect file /data/assets/agg_vk.vkey\n"
        rm /data/assets/agg_vk.vkey
        fi
        fi

        if [ -f /data/assets/evm_verifier.bin ]; then
        if ! check_shasum "/data/assets/evm_verifier.bin" "$VRFR_SHASUM"; then
        echo "Removing incorrect file /data/assets/evm_verifier.bin\n"
        rm /data/assets/evm_verifier.bin
        fi
        fi

        if [ -f /data/assets/layer2.config ]; then
        if ! check_shasum "/data/assets/layer2.config" "$CFG2_SHASUM"; then
        echo "Removing incorrect file /data/assets/layer2.config\n"
        rm /data/assets/layer2.config
        fi
        fi

        if [ -f /data/assets/layer4.config ]; then
        if ! check_shasum "/data/assets/layer4.config" "$CFG4_SHASUM"; then
        echo "Removing incorrect file /data/assets/layer4.config\n"
        rm /data/assets/layer4.config
        fi
        fi


        # download missing files

        if [ ! -f /data/params/params24 ]; then
        mkdir -p /data/params
        echo "Downloading /data/params/params24..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/setup/params24 -O /data/params/params24
        echo "Download completed\n"
        if ! check_shasum "/data/params/params24" "$PARAMS24_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/params/params26 ]; then
        mkdir -p /data/params
        echo "Downloading /data/params/params26..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/setup/params26 -O /data/params/params26
        echo "Download completed\n"
        if ! check_shasum "/data/params/params26" "$PARAMS26_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/assets/chunk_vk.vkey ]; then
        mkdir -p /data/assets
        echo "Downloading /data/assets/chunk_vk.vkey..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/chunk_vk.vkey -O /data/assets/chunk_vk.vkey
        echo "Download completed\n"
        if ! check_shasum "/data/assets/chunk_vk.vkey" "$CHUNK_VK_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/assets/agg_vk.vkey ]; then
        mkdir -p /data/assets
        echo "Downloading /data/assets/agg_vk.vkey..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/agg_vk.vkey -O /data/assets/agg_vk.vkey
        echo "Download completed\n"
        if ! check_shasum "/data/assets/agg_vk.vkey" "$BATCH_VK_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/assets/evm_verifier.bin ]; then
        mkdir -p /data/assets
        echo "Downloading /data/assets/evm_verifier.bin..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/evm_verifier.bin -O /data/assets/evm_verifier.bin
        echo "Download completed\n"
        if ! check_shasum "/data/assets/evm_verifier.bin" "$VRFR_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/assets/layer2.config ]; then
        mkdir -p /data/assets
        echo "Downloading /data/assets/layer2.config..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/layer2.config -O /data/assets/layer2.config
        echo "Download completed\n"
        if ! check_shasum "/data/assets/layer2.config" "$CFG2_SHASUM"; then exit 1; fi
        fi

        if [ ! -f /data/assets/layer4.config ]; then
        mkdir -p /data/assets
        echo "Downloading /data/assets/layer4.config..."
        wget https://circuit-release.s3.us-west-2.amazonaws.com/release-$RELEASE_VERSION/layer4.config -O /data/assets/layer4.config
        echo "Download completed\n"
        if ! check_shasum "/data/assets/layer4.config" "$CFG4_SHASUM"; then exit 1; fi
        fi
#  config:
#    enabled: true
#    data:
#      config.json: |
#        {
#          "prover_manager": {
#            "provers_per_session": 1,
#            "session_attempts": 100,
#            "chunk_collection_time_sec": 3600,
#            "batch_collection_time_sec": 600,
#            "verifier": {
#              "fork_name": "bernoulli",
#              "mock_mode": false,
#              "params_path": "/verifier/params",
#              "assets_path": "/verifier/assets"
#            },
#            "max_verifier_workers": 4,
#            "min_prover_version": "v4.3.41"
#          },
#          "db": {
#            "driver_name": "postgres",
#            "dsn": "postgres://postgres:qwerty12345@postgresql:5432/scroll",
#            "maxOpenNum": 200,
#            "maxIdleNum": 20
#          },
#          "l2": {
#            "chain_id": 222222
#          },
#          "auth": {
#            "secret": "XXX",
#            "challenge_expire_duration_sec": 10,
#            "login_expire_duration_sec": 3600
#          }
#        }

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s
