---
global:
  nameOverride: &app_name coordinator-cron
  fullnameOverride: *app_name

image:
  repository: scrolltech/coordinator-cron
  pullPolicy: Always
  tag: v4.4.22

env:
  - name: HTTP_PORT
    value: "8555"
  - name: WS_PORT
    value: "8556"
  - name: RUST_LOG
    value: info
  - name: METRICS_PORT
    value: "8090"
  - name: GIN_MODE
    value: "release"

command: [
  "/bin/sh",
  "-c",
  "coordinator_cron --config /app/conf/coordinator-config.json \
    --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} \
    --log.debug",
]

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: yes
    type: configMap
    mountPath: /app/conf/
    name: coordinator-config
  genesis:
    enabled: yes
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/health"
      port: 8090

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s
