{
 "title": "coordinator-api",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "P99", "query": "0.5,0.75,0.9,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  { "title": "API QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "/coordinator/v1/challenge QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/challenge\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/challenge\"}[$__rate_interval])) by (instance, uri, code)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/coordinator/v1/login QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/login\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/login\"}[$__rate_interval])) by (instance, uri, code)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/coordinator/v1/get_task QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/get_task\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/get_task\"}[$__rate_interval])) by (instance, uri, code)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  {
   "title": "/coordinator/v1/submit_proof QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/submit_proof\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(coordinator_uri_request_total{uri=\"/coordinator/v1/submit_proof\"}[$__rate_interval])) by (instance ,uri, code)",
     "legendFormat": "{{instance}}-code-{{code}}"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "/coordinator/v1/challenge Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le,instance)(irate(coordinator_request_duration_bucket{uri=\"/coordinator/v1/challenge\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "/coordinator/v1/login Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le,instance)(irate(coordinator_request_duration_bucket{uri=\"/coordinator/v1/login\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "/coordinator/v1/get_task Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le,instance)(irate(coordinator_request_duration_bucket{uri=\"/coordinator/v1/get_task\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "/coordinator/v1/submit_proof Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(${P99}, sum by (le, instance)(irate(coordinator_request_duration_bucket{uri=\"/coordinator/v1/submit_proof\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  { "title": "Coordinator get task status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "batch get task total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "coordinator_batch_get_task_total",
     "legendFormat": "{{instance}}-{{fork_name}}"
    }
   ]
  },
  {
   "title": "chunk get task total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "coordinator_chunk_get_task_total",
     "legendFormat": "{{instance}}-{{fork_name}}"
    }
   ]
  },
  {
   "title": "get batches by prover (every 30m in average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(coordinator_get_task_count{env = \"mainnet\", task_type=\"batch\"}[30m])) by (prover_pubkey, prover_name)",
     "legendFormat": "{{prover_name}}-pubkey-{{prover_pubkey}}"
    }
   ]
  },
  {
   "title": "get chunks by prover (every 30m in average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(coordinator_get_task_count{env = \"${env}\", task_type=\"chunk\"}[30m])) by (prover_pubkey, prover_name)",
     "legendFormat": "{{prover_name}}-pubkey-{{prover_pubkey}}"
    }
   ]
  },
  {
   "title": "inactive prover in last 30m",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(changes(coordinator_get_task_access_count{env = \"${env}\"}[30m])) by (prover_pubkey, prover_name) == 0",
     "legendFormat": "{{prover_name}}-pubkey-{{prover_pubkey}}"
    }
   ]
  },
  {
   "title": "Coordinator submit proof status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "coordinator_submit_proof total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "targets": [
      { "expr": "coordinator_submit_proof_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "coordinator_submit_proof_failure_total total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "coordinator_submit_proof_failure_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "verifier total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "targets": [
      { "expr": "coordinator_verifier_total", "legendFormat": "{{instance}}-{{version}}" }
     ]
    },
    {
     "title": "verifier failure total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "coordinator_verifier_failure_total",
       "legendFormat": "{{instance}}-{{version}}"
      }
     ]
    },
    {
     "title": "Proof success duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "histogram_quantile(${P99}, sum by (le)(irate(coordinator_task_prove_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{instance}}-total"
      }
     ]
    },
    {
     "title": "validate failure",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "coordinator_validate_failure_total",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "coordinator_validate_failure_submit_twice_total",
       "legendFormat": "{{instance}}-submit_twice"
      },
      {
       "expr": "coordinator_validate_failure_submit_status_not_ok",
       "legendFormat": "{{instance}}-submit-status-failure"
      },
      {
       "expr": "coordinator_validate_failure_submit_timeout",
       "legendFormat": "{{instance}}-have-timeout"
      },
      {
       "expr": "coordinator_validate_failure_submit_have_been_verifier",
       "legendFormat": "{{instance}}-have-verifier"
      }
     ]
    }
   ]
  }
 ]
}