{
 "title": "coordinator-cron",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "P99", "query": "0.5,0.75,0.9,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  { "title": "Coordinator cron status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "check task timeout total rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(coordinator_batch_timeout_checker_run_total[$__rate_interval])",
     "legendFormat": "{{instance}}-batch"
    },
    {
     "expr": "rate(coordinator_chunk_timeout_checker_run_total[$__rate_interval])",
     "legendFormat": "{{instance}}-chunk"
    }
   ]
  },
  {
   "title": "check timeout reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "coordinator_batch_prover_task_timeout_total",
     "legendFormat": "{{instance}}-batch"
    },
    {
     "expr": "coordinator_chunk_prover_task_timeout_total",
     "legendFormat": "{{instance}}-chunk"
    }
   ]
  },
  {
   "title": "check batch all chunks ready total rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "coordinator_check_batch_all_chunk_ready_run_total",
     "legendFormat": "{{instance}}-batch"
    }
   ]
  }
 ]
}