---
l1-devnet:
  enabled: false

blockscout:
  enabled: false

bridge-history-api:
  enabled: false

bridge-history-fetcher:
  enabled: false

balance-checker:
  enabled: false

chain-monitor:
  enabled: false

contracts:
  enabled: false

coordinator-api:
  enabled: false

coordinator-cron:
  enabled: false

event-watcher:
  enabled: false

frontends:
  enabled: false

gas-oracle:
  enabled: false

grafana:
  enabled: false

rollup-explorer-backend:
  enabled: false

rollup-node:
  enabled: false

l1-explorer:
  enabled: false

l2-sequencer:
  enabled: false

l2-rpc:
  enabled: false

l2-bootnode:
  enabled: false

loki-stack:
  enabled: false

blockscout-sc-verifier:
  enabled: false

rpc-gateway:
  enabled: false

postgresql:
  enabled: true
  nameOverride: postgresql
  fullnameOverride: postgresql
  auth:
    enablePostgresUser: true
    postgresPassword: "qwerty12345"
  volumePermissions:
    enabled: true
  primary:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenDeleted: Delete
      whenScaled: Delete
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
    extendedConfiguration: |
      max_connections = 400
  tls:
    enabled: true
    autoGenerated: true


kube-prometheus-stack:
  enabled: false

# -- Database connection information. These will be used by init containers to create database, users and roles for
# -- each services. A user with admin privilege is required.
db:
  pg_host: "postgresql"
  pg_user: "postgres"
  pg_password: "qwerty12345"
  pg_port: "5432"
  bridge_history_password: "test1234"
  chain_monitor_password: "test1234"
  event_watcher_password: "test1234"
  gas_oracle_password: "test1234"
  rollup_node_password: "test1234"
  rpc_gateway_password: "test1234"
