---
global:
  nameOverride: &app_name gas-oracle
  fullnameOverride: *app_name

image:
  repository: scrolltech/gas-oracle
  pullPolicy: Always
  tag: v4.4.71

command:
  [
    "/bin/sh",
    "-c",
    "gas_oracle --config /app/conf/rollup-config.json --genesis /app/genesis/genesis.json --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} --log.debug"
  ]

podLabels:
  app: *app_name
  dbaccess: "true"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: true
    type: configMap
    mountPath: /app/conf/
    name: gas-oracle-config
  genesis:
    enabled: true
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config
  migrate-db:
    enabled: true
    type: configMap
    mountPath: /config/migrate-db.json
    name: gas-oracle-migrate-db
    defaultMode: "0777"
  wait-for-l1-script:
    enabled: true
    type: configMap
    name: wait-for-l1-script
    defaultMode: "0777"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/health"
      port: 8090

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

env:
  - name: METRICS_PORT
    value: 8090

envFrom:
  - configMapRef:
      name: gas-oracle-env

initContainers:
  1-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(SCROLL_ROLLUP_DB_CONFIG_DSN)
      - --timeout
      - "0"
    envFrom:
      - configMapRef:
          name: gas-oracle-env
  2-migrate-db:
    image: scrolltech/rollup-db-cli:v4.4.60
    command: ["/bin/sh", "-c", "db_cli migrate --config /config/migrate-db.json"]
    volumeMounts:
      - name: migrate-db
        mountPath: /config/migrate-db.json
        subPath: migrate-db.json
    envFrom:
      - configMapRef:
          name: gas-oracle-env
  3-wait-for-l1:
    image: scrolltech/scroll-alpine:v0.0.1
    command:
      - /bin/sh
      - -c
      - /wait-for-l1.sh $SCROLL_L1_RPC
    envFrom:
      - configMapRef:
          name: gas-oracle-env
    volumeMounts:
      - name: wait-for-l1-script
        mountPath: /wait-for-l1.sh
        subPath: wait-for-l1.sh
  4-wait-for-l2-sequencer:
    image: atkrad/wait4x:latest
    args:
      - http
      - http://l2-sequencer:8545
      - --expect-status-code
      - "200"
      - --timeout
      - "0"

configMaps:
  migrate-db:
    enabled: true
    data:
      migrate-db.json: |
        {
            "driver_name": "postgres",
            "dsn": ""
        }

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-sdk
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s

scrollConfig: |
  {}
