---
global:
  nameOverride: &app_name l2-bootnode
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: statefulset

image:
  repository: scrolltech/l2geth
  pullPolicy: Always
  tag: v5.2.1-arm64

env:
  - name: L2GETH_ROLE
    value: "bootnode"
  - name: CHAIN_ID
    value: "222222"
  - name: L2GETH_NODEKEY
    value: "9c680a1af21330dd8063efa096997899d29c51917a94e805b895e9147d213842"
  - name: L2GETH_PEER_LIST
    value: '["enode://848a7d59dd8f60dd1a51160e6bc15c194937855443de9be4b2abd83e11a5c4ac21d61d065448c5c520826fe83f1f29eb5a452daccca27b8113aa897074132507@l2-sequencer:30303"]'
  - name: L2GETH_L1_CONTRACT_DEPLOYMENT_BLOCK
    value: "0"
  - name: L2GETH_L1_ENDPOINT
    value: "http://l1-devnet:8545"
  - name: L2GETH_L1_WATCHER_CONFIRMATIONS
    value: "0x6"
  - name: L2GETH_P2P_PORT
    value: &p2p_port 30303
  - name: L2GETH_PPROF_PORT
    value: &pprof_port 6060

command: ["bash",
  "-c",
  "/script/l2geth-boot.sh"
]

initContainers:
  wait-for-other-pod:
    image: curlimages/curl
    args:
      - /bin/sh
      - -c
      - >
        set -x;
        while [ $(curl -sw '%{http_code}' "l1-devnet:8545/api" -o /dev/null) -ne 404 ]; do
          sleep 5;
        done

defaultProbes: &default_probes
  enabled: false
  custom: true
  spec:
    httpGet:
      path: "/"
      port: *p2p_port

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes

persistence:
  boot:
    enabled: yes
    type: configMap
    mountPath: /script/
    name: l2geth-boot
    defaultMode: 0777
  data:
    enabled: yes
    type: pvc
    mountPath: /l2geth/data
    accessMode: ReadWriteOnce
    size: 10Gi
  genesis:
    enabled: yes
    type: configMap
    mountPath: /l2geth/genesis/
    name: genesis-config

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: *p2p_port
      metrics:
        enabled: true
        port: *pprof_port
        targetPort: *pprof_port

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s
        path: /debug/metrics/prometheus