global:
  nameOverride: &app_name frontends
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: deployment

image:
  repository: scrolltech/frontends
  pullPolicy: Always
  tag: 2.2.4

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
    annotations:
      external-dns.alpha.kubernetes.io/hostname: scroll-stack-frontends.devnet.scroll.tech
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    type: LoadBalancer

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes
