{{- if .Values.global.isStandalone }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-history-api-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  bridge-history-config.json : |
{{ .Values.scrollConfig | indent 4 }}
---
{{- end }}
