- name: init go-prover
  hosts: "{{env}}_{{type}}"
  gather_facts: true
  max_fail_percentage: 0
  serial: 10
  vars_files:
    - vars/shared-vars.yaml
  vars:
    env: "{{env}}"
    type: "{{type}}"
    proof_type: "{{vars[type]['proof_type']}}"
  roles:
    - role: deploy
      tags: deploy
