---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-cron-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  coordinator-cron-config.json: |
{{ .Values.scrollConfig | indent 4 }}
