---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-api-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  coordinator-config.json: |
{{ .Values.scrollConfig | indent 4 }}
