{{- define "scrolllib.externalsecrets.tpl" -}}
{{- range $key,$values := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ $key }}
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $values.serviceAccount }}
      region: {{ $values.secretRegion | default "us-west-2" }}
      service: SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  data:
    {{- toYaml $values.data | nindent 4 }}
  refreshInterval: {{ $values.refreshInterval | default "5m" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $key }}
  target:
    creationPolicy: {{ $values.creationPolicy | default "Owner" }}
    deletionPolicy: {{ $values.deletionPolicy | default "Retain" }}
    name: {{ $key }}
---
{{- end -}}
{{- end -}}
