global:
  isStandalone: true

controller:
  replicas: 2

initContainers:
  1-wait-for-postgres:
    image: atkrad/wait4x:latest
    args:
      - tcp
      - $(DATABASE_HOST):$(DATABASE_PORT)
      - --timeout
      - "0"
    envFrom:
      - configMapRef:
          name: coordinator-cron-env
  2-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(DATABASE_URL)
      - --timeout
      - "0"
    envFrom:
      - secretRef:
          name: coordinator-cron-secret-env

configMaps:
  env:
    enabled: true
    data:
      DATABASE_HOST: "postgresql"
      DATABASE_PORT: "5432"

ingress:
  main:
    ingressClassName: "nginx"
    hosts:
      - host: coordinator-api-2.devnet.scroll.tech
        paths:
          - path: /
            pathType: Prefix

externalSecrets:
  coordinator-cron-secret-env:
    data:
      - remoteRef:
          key: scroll/coordinator-secret-env
          property: DATABASE_URL
        secretKey: DATABASE_URL
    refreshInterval: 2m
    serviceAccount: external-secrets
