global:
  isStandalone: true

persistence:
  #TODO is it still needed or can I use the default value ?
  gas-oracle:
    enabled: true
    type: configMap
    mountPath: /app/conf/
    name: gas-oracle-config
  migrate-db:
    enabled: true
    type: secret
    mountPath: /config/migrate-db.json
    name: gas-oracle-migrate-db
    defaultMode: "0777"

envFrom:
  - secretRef:
      name: gas-oracle-secret-env

initContainers:
  1-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(SCROLL_ROLLUP_DB_CONFIG_DSN)
      - --timeout
      - "0"
    envFrom:
      - secretRef:
          name: gas-oracle-secret-env

configMaps:
  env:
    enabled: true
    data:
      SCROLL_L1_RPC: ""
  migrate-db:
    enabled: false

externalSecrets:
  gas-oracle-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_DB_CONFIG_DSN
        secretKey: SCROLL_ROLLUP_DB_CONFIG_DSN
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L1_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L1_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_PRIVATE_KEY
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_PRIVATE_KEY
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_COMMIT_SENDER_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_COMMIT_SENDER_PRIVATE_KEY
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_FINALIZE_SENDER_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_FINALIZE_SENDER_PRIVATE_KEY
    refreshInterval: 2m
    serviceAccount: external-secrets
  gas-oracle-migrate-db:
    provider: aws
    data:
      - remoteRef:
          key: scroll/gas-oracle-migrate-db
        secretKey: migrate-db.json
    refreshInterval: 2m
    serviceAccount: external-secrets
