apiVersion: v2
description: External secrets function library for Helm charts
keywords:
- external-secrets
- secret-store
- library
kubeVersion: '>=1.22.0-0'
maintainers:
- email: sebastien@scroll.io
  name: scroll-tech
name: external-secrets-lib
type: library
version: 0.0.2
