---
apiVersion: v2
description: rollup-relayer helm charts
name: rollup-relayer
version: 0.0.1
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-sre
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.2.1