balance-checker:
  enabled: false
blockscout:
  enabled: true
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: blockscout.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true
blockscout-sc-verifier:
  enabled: false
bridge-history-api:
  enabled: true
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: bridge-history-api.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true

bridge-history-fetcher:
  enabled: true

chain-monitor:
  enabled: true

contracts:
  enabled: false

coordinator-api:
  enabled: true
  ingress:
    main:
      enabled: true
      hosts:
        - host: coordinator-api.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix

coordinator-cron:
  enabled: true

db:
  bridge_history_password: test1234
  chain_monitor_password: test1234
  event_watcher_password: test1234
  gas_oracle_password: test1234
  pg_host: postgresql
  pg_password: qwerty12345
  pg_port: "5432"
  pg_user: postgres
  rollup_node_password: test1234
  rpc_gateway_password: test1234

frontends:
  enabled: true
  ingress:
    main:
      enabled: true
      hosts:
        - host: frontends.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix

gas-oracle:
  enabled: true

grafana:
  adminPassword: scroll-stack
  adminUser: admin
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - disableDeletion: false
          editable: true
          folder: scroll
          name: default
          options:
            path: /var/lib/grafana/dashboards/default/
          orgId: 1
          type: file
  dashboardsConfigMaps:
    default: grafana-dashboards
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - access: proxy
          isDefault: true
          jsonData:
            timeInterval: 30s
          name: Prometheus
          type: prometheus
          url: http://prometheus-prometheus:9090
        - access: proxy
          jsonData:
            httpHeaderName1: X-Scope-OrgID
            secureJsonData:
              httpHeaderValue1: "1"
          name: Loki
          type: loki
          url: http://loki:3100
  enabled: true
  fullnameOverride: grafana
  ingress:
    enabled: true
    hosts:
      - grafana.devnet.scroll.tech
    ingressClassName: nginx
  nameOverride: grafana
kube-prometheus-stack:
  alertmanager:
    enabled: false
  enabled: true
  fullnameOverride: prometheus
  grafana:
    enabled: false
  kube-state-metrics:
    fullnameOverride: kube-state-metrics
    nameOverride: kube-state-metrics
  nameOverride: prometheus
  prometheus:
    enabled: true
  prometheus-node-exporter:
    fullnameOverride: node-exporter
    nameOverride: node-exporter

l1-devnet:
  enabled: true
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: l1.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true

l1-explorer:
  enabled: true
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: l1-explorer.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true

l2-bootnode:
  enabled: true
  image:
    tag: scroll-v5.2.0

l2-rpc:
  enabled: true
  image:
    tag: scroll-v5.2.0
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: l2-rpc.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
    startup:
      enabled: false

l2-sequencer:
  enabled: true
  image:
    tag: scroll-v5.2.0
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
    startup:
      enabled: false
loki-stack:
  enabled: true
  loki:
    fullnameOverride: loki
    nameOverride: loki
  promtail:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
    enabled: false
    fullnameOverride: promtail
    nameOverride: promtail
postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: qwerty12345
  enabled: true
  fullnameOverride: postgresql
  nameOverride: postgresql
  primary:
    extendedConfiguration: |
      max_connections = 400
    livenessProbe:
      enabled: false
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenDeleted: Delete
      whenScaled: Delete
    readinessProbe:
      enabled: false
    resources:
      limits:
        cpu: 3
        memory: 1024Mi
      requests:
        cpu: 2
        memory: 512Mi
    startupProbe:
      enabled: false
  tls:
    autoGenerated: true
    enabled: true
  volumePermissions:
    enabled: true
rollup-explorer-backend:
  enabled: true
  ingress:
    main:
      annotations: {}
      enabled: true
      hosts:
        - host: rollup-explorer-backend.devnet.scroll.tech
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: nginx
      labels: {}
      primary: true
rollup-node:
  enabled: true
rpc-gateway:
  enabled: true