configMaps:
  env:
    enabled: true
    data:
      CHAIN_ID: ""
      L2GETH_L1_ENDPOINT: ""
      L2GETH_L1_CONTRACT_DEPLOYMENT_BLOCK: ""

ingress:
  main:
    ingressClassName: "nginx"
    hosts:
      - host: l2-rpc.scrollsdk
        paths:
          - path: /
            pathType: Prefix
