---
global:
  nameOverride: &app_name l1-explorer
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: Recreate
  type: deployment

image:
  repository: blockscout/blockscout
  pullPolicy: Always
  tag: 6.6.0

env:
  - name: CHAIN_ID
    value: 111111
  - name: DATABASE_URL
    value: "postgresql://postgres:qwerty12345@postgresql:5432/l1-explorer"
  - name: ECTO_USE_SSL
    value: false
  - name: ETHEREUM_JSONRPC_HTTP_URL
    value: http://l1-devnet:8545
  - name: ETHEREUM_JSONRPC_TRACE_URL
    value: http://l1-devnet:8545
  - name: ETHEREUM_JSONRPC_VARIANT
    value: geth
  - name: ETHEREUM_JSONRPC_WS_URL
    value: ws://l1-devnet:8546
  - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
    value: true
  - name: PORT
    value: 3000
  - name: NETWORK
    value: [""]
  - name: COIN
    value: ETH
  - name: COIN_NAME
    value: ETH
  - name: LOGO
    value: /images/logo.svg
  - name: WEBAPP_URL
    value: https://l1-explorer.scroll.tech
  - name: BLOCKSCOUT_HOST
    value: test-l1-explorer.scroll.io
  - name: JSON_RPC
    value: http://l1-devnet:8545
  - name: SUBNETWORK
    value: "Scroll Sepolia Testnet"
  - name: SUPPORTED_CHAINS
    value: '[{ "title": "Scroll SDK (L1)", "url": "https://localhost:3000", "test_net?": true }, { "title": "Scroll SDK (L2) Testnet", "url": "http://blockscout:3000", "test_net?": true }]'
  - name: DISABLE_EXCHANGE_RATES
    value: true
  - name: BLOCKSCOUT_VERSION
    value: 5.2.1
  - name: FOOTER_GITHUB_LINK
    value: https://github.com/blockscout/blockscout
  - name: ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT
    value: 10s
  - name: INDEXER_MEMORY_LIMIT
    value: 10gb
  - name: BLOCK_TRANSFORMER
    value: clique
  - name: MICROSERVICE_SC_VERIFIER_ENABLED
    value: true

command: [
  "/bin/sh",
  "-c",
  "/app/bin/blockscout start"
]

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 3000

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 3000

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes


persistence:
  init-db:
    enabled: yes
    type: configMap
    mountPath: /init-db.sh
    name: init-db
    defaultMode: "0777"

initContainers:
  1-wait-for-postgres:
    image: atkrad/wait4x:latest
    args:
      - tcp
      - postgresql:5432
      - --timeout
      - "0"
  2-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable
      - --timeout
      - "0"
  3-migrate-db:
    image: blockscout/blockscout:6.6.0
    env:
    - name: DATABASE_URL
      value: "postgresql://postgres:qwerty12345@postgresql:5432/l1-explorer"
    command: ["/bin/sh","-c","/app/bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\""]

ingress:
  main:
    enabled: true
    primary: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: l1-explorer.devnet.scroll.tech
        paths:
          - path: /
            pathType: Prefix
