---
apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-checker-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  config.json : |
{{ .Values.scrollConfig | nindent 4 }}
