{
 "title": "event_watcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "L2 watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fetch contract event  running",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rollup_l2_watcher_fetch_contract_events_total{instance=\"${instance}\", service=\"event-watcher\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": " fetch contract height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rollup_l2_watcher_fetch_contract_height{instance=\"${instance}\", service=\"event-watcher\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "msg relayed event rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(rollup_l2_watcher_msg_relayed_events_total{instance=\"${instance}\", service=\"event-watcher\"}[$__rate_interval])",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  { "title": "L1 Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "fetch contract event  running",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rollup_l1_watcher_fetch_block_contract_event_total{instance=\"${instance}\", service=\"event-watcher\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": " fetch contract sent event rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(rollup_l1_watcher_fetch_block_contract_event_sent_event_total{instance=\"${instance}\", service=\"event-watcher\"}[$__rate_interval])",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "fetch contract rollup event rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(rollup_l1_watcher_fetch_block_contract_event_rollup_event_total{instance=\"${instance}\", service=\"event-watcher\"}[$__rate_interval])",
     "legendFormat": "${instance}-total"
    }
   ]
  }
 ]
}