{
 "title": "gas_oracle",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "L1 Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pull latest L1 blocks running",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rollup_l1_watcher_fetch_block_header_total{instance=\"${instance}\", service=\"gas-oracle\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "fetch block header height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rollup_l1_watcher_fetch_block_header_processed_block_height{instance=\"${instance}\", service=\"gas-oracle\"}",
     "legendFormat": "${instance}-total"
    }
   ]
  },
  {
   "title": "Gas oracle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "layer1 gas price oracler running",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer1_gas_price_oracler_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "layer2 gas price oracler running",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer2_gas_price_oracler_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "relayer l1 latest gas price ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer1_gas_price_latest_gas_price{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "relayer l2 latest gas price ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer2_gas_price_latest_gas_price{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "layer1 gas price oracle confirmed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer1_update_gas_oracle_confirmed_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "layer2 gas price oracle confirmed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer2_update_layer1_gas_oracle_confirmed_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "layer1 gas price oracle failed confirmed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer1_update_gas_oracle_confirmed_failed_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "layer2 gas price oracle failed confirmed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_layer2_update_layer1_gas_oracle_confirmed_failed_total{instance=\"${instance}\", service=\"gas-oracle\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    }
   ]
  },
  { "title": "L1 gas oracle Sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "sending transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(rollup_sender_send_transaction_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}[$__rate_interval])",
     "legendFormat": "{{exported_service}}--{{name}}"
    }
   ]
  },
  {
   "title": "re-sending transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}[$__rate_interval])",
     "legendFormat": "{{exported_service}}-{{name}}"
    }
   ]
  },
  {
   "title": "sender failure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rollup_sender_send_transaction_full_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}-channel-full"
    },
    {
     "expr": "rollup_sender_send_transaction_full_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}-repeat-transaction"
    },
    {
     "expr": "rollup_sender_send_transaction_get_fee_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}-get-fee-failure"
    },
    {
     "expr": "rollup_sender_send_transaction_send_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}-send-tx-failure"
    }
   ]
  },
  {
   "title": "re-sending transaction failure rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_failed_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}[$__rate_interval])",
     "legendFormat": "{{exported_service}}-{{name}}"
    }
   ]
  },
  {
   "title": "current gas limit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rollup_sender_gas_limit{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}"
    }
   ]
  },
  {
   "title": "current gas price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rollup_sender_gas_price_cap{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l1_relayer\"}",
     "legendFormat": "{{exported_service}}-{{name}}"
    }
   ]
  },
  {
   "title": "L2 gas oracle Sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "sending transaction rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}[$__rate_interval])",
       "legendFormat": "{{exported_service}}--{{name}}"
      }
     ]
    },
    {
     "title": "re-sending transaction rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}[$__rate_interval])",
       "legendFormat": "{{exported_service}}--{{name}}"
      }
     ]
    },
    {
     "title": "sender failure",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rollup_sender_send_transaction_full_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}-channel-full"
      },
      {
       "expr": "rollup_sender_send_transaction_full_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}-repeat-transaction"
      },
      {
       "expr": "rollup_sender_send_transaction_get_fee_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}-get-fee-failure"
      },
      {
       "expr": "rollup_sender_send_transaction_send_tx_failure_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}-send-tx-failure"
      }
     ]
    },
    {
     "title": "re-sending transaction failure rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_failed_total{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}[$__rate_interval])",
       "legendFormat": "{{exported_service}}--{{name}}"
      }
     ]
    },
    {
     "title": "current gas tip cap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rollup_sender_gas_tip_cap{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}"
      }
     ]
    },
    {
     "title": "current gas fee cap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rollup_sender_gas_fee_cap{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}"
      }
     ]
    },
    {
     "title": "current gas limit",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rollup_sender_gas_limit{instance=\"${instance}\", service=\"gas-oracle\", exported_service=\"l2_relayer\"}",
       "legendFormat": "{{exported_service}}-{{name}}"
      }
     ]
    }
   ]
  }
 ]
}