{{- if index .Values "balance-checker" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: balance-checker-config
data:
{{ (.Files.Glob "balance-checker-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: balance-checker-env
data:
{{ (.Files.Glob "configs/balance-checker.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "blockscout" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: blockscout-env
data:
{{ (.Files.Glob "configs/blockscout.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "bridge-history-api" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: bridge-history-config
data:
{{ (.Files.Glob "bridge-history-config.json").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "rollup-node" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: rollup-node-config
data:
{{ (.Files.Glob "rollup-config.json").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "chain-monitor" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: chain-monitor-config
data:
{{ (.Files.Glob "chain-monitor-config.json").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "coordinator-api" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: coordinator-config
data:
{{ (.Files.Glob "coordinator-config.json").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "frontends" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: frontends-config
data:
{{ (.Files.Glob ".env.frontend").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "l1-devnet" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l1-devnet-env
data:
{{ (.Files.Glob "configs/l1-devnet.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "l1-explorer" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l1-explorer-env
data:
{{ (.Files.Glob "configs/l1-explorer.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-bootnode" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-bootnode-env
data:
{{ (.Files.Glob "configs/l2-bootnode.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-rpc" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-rpc-env
data:
{{ (.Files.Glob "configs/l2-rpc.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-sequencer" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-sequencer-env
data:
{{ (.Files.Glob "configs/l2-sequencer.env").AsConfig | indent 2 }}
---
{{- end }}