apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
data:
  PG_HOST: {{ .Values.db.pg_host | b64enc }}
  PG_USER: {{ .Values.db.pg_user | b64enc }}
  PGPASSWORD: {{ .Values.db.pg_password | b64enc }}
  PG_PORT: {{ .Values.db.pg_port | b64enc }}
  BRIDGE_HISTORY_PASSWORD: {{ .Values.db.bridge_history_password | b64enc }}
  CHAIN_MONITOR_PASSWORD: {{ .Values.db.chain_monitor_password | b64enc }}
  EVENT_WATCHER_PASSWORD: {{ .Values.db.event_watcher_password | b64enc }}
  GAS_ORACLE_PASSWORD: {{ .Values.db.gas_oracle_password | b64enc }}
  ROLLUP_RELAYER_PASSWORD: {{ .Values.db.rollup_relayer_password | b64enc }}
  RPC_GATEWAY_PASSWORD:  {{ .Values.db.rpc_gateway_password | b64enc }}
type: Opaque
