apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: rollup-explorer-config
data:
  config.json: |
    {
      "bind_port": "8080",
      "metrics_bind_port": "19130",
      "db_url" : "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable",
      "open_api_addr" : "/rollupscan",
      "max_per_page": 500
    }