---
global:
  nameOverride: &app_name gas-oracle
  fullnameOverride: *app_name

image:
  repository: scrolltech/gas-oracle
  pullPolicy: Always
  tag: v4.3.92-test-platform-amd64-3

command:
  [
    "/bin/sh",
    "-c",
    "gas_oracle --config /app/conf/config.json --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} --log.debug"
  ]

podLabels:
  app: *app_name
  dbaccess: "true"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: yes
    type: configMap
    mountPath: /app/conf/
    name: gas-oracle-config
    items:
      - key: config.json
        path: config.json
  genesis:
    enabled: yes
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config
    subPath: genesis.json
  init-db:
    enabled: yes
    type: configMap
    mountPath: /init-db.sh
    name: init-db
    defaultMode: "0777"
  migrate-db:
    enabled: yes
    type: configMap
    mountPath: /config/migrate-db.json
    name: gas-oracle-migrate-db
    defaultMode: "0777"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/health"
      port: 8090

probes:
  liveness:
    << : *default_probes
  readiness:
    << : *default_probes
  startup:
    << : *default_probes

env:
  - name: METRICS_PORT
    value: 8090

initContainers:
  init-db:
    image: postgres:latest
    env:
      - name: POSTGRES_DB
        value: scroll
      - name: PG_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_USER
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PGPASSWORD
      - name: PG_HOST
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_HOST
      - name: PG_PORT
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: PG_PORT
      - name: DB_USER
        value: gas_oracle
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: GAS_ORACLE_PASSWORD
    command: ["bash","-c","./init-db.sh"]
    volumeMounts:
      - name: init-db
        mountPath: /init-db.sh
        subPath: init-db.sh
  migrate-db:
    image: scrolltech/rollup-db-cli
    command: ["/bin/sh","-c","db_cli migrate --config /config/migrate-db.json"]
    volumeMounts:
      - name: migrate-db
        mountPath: /config/migrate-db.json
        subPath: migrate-db.json

configMaps:
  config:
    enabled: true
    data:
      config.json: |
        {
          "l1_config": {
            "confirmations": "0x6",
            "endpoint": "http://l1-devnet:8545",
            "l1_message_queue_address": "0x08275d41f29bF787D28Ed4a706e29781104d41cd",
            "scroll_chain_address": "0x9Af51261a1f324Df094dc8028F2E5259C23B5336",
            "start_height": 0,
            "relayer_config": {
              "gas_price_oracle_contract_address": "0x5300000000000000000000000000000000000002",
              "sender_config": {
                "endpoint": "http://l2-sequencer:8545",
                "escalate_blocks": 100,
                "escalate_multiple_num": 11,
                "escalate_multiple_den": 10,
                "max_gas_price": 10000000000000,
                "tx_type": "LegacyTx",
                "check_pending_time": 3,
                "confirmations": "0x6"
              },
              "gas_oracle_config": {
                "min_gas_price": 0,
                "gas_price_diff": 50000,
                "l1_base_fee_weight": 0.132,
                "l1_blob_base_fee_weight": 0.145
              },
              "gas_oracle_sender_private_key": "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
            }
          },
          "l2_config": {
            "confirmations": "0x6",
            "endpoint": "http://l2-sequencer:8545",
            "l2_message_queue_address": "0x5300000000000000000000000000000000000000",
            "relayer_config": {
              "rollup_contract_address": "0x9Af51261a1f324Df094dc8028F2E5259C23B5336",
              "gas_price_oracle_contract_address": "0x08275d41f29bF787D28Ed4a706e29781104d41cd",
              "sender_config": {
                "endpoint": "http://l1-devnet:8545",
                "escalate_blocks": 4,
                "escalate_multiple_num": 12,
                "escalate_multiple_den": 10,
                "max_gas_price": 200000000000,
                "max_blob_gas_price": 200000000000,
                "tx_type": "DynamicFeeTx",
                "check_pending_time": 10,
                "confirmations": "0x6"
              },
              "gas_oracle_config": {
                "min_gas_price": 0,
                "gas_price_diff": 50000
              },
              "chain_monitor": {
                "enabled": false,
                "timeout": 3,
                "try_times": 5,
                "base_url": "http://localhost:8749"
              },
              "enable_test_env_bypass_features": true,
              "finalize_batch_without_proof_timeout_sec": 3600,
              "gas_oracle_sender_private_key": "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6",
              "commit_sender_private_key": "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
              "finalize_sender_private_key": "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
              "l1_commit_gas_limit_multiplier": 1.2
            },
            "chunk_proposer_config": {
              "max_block_num_per_chunk": 100,
              "max_tx_num_per_chunk": 100,
              "max_l1_commit_gas_per_chunk": 5000000,
              "max_l1_commit_calldata_size_per_chunk": 123740,
              "chunk_timeout_sec": 720000,
              "max_row_consumption_per_chunk": 1000000,
              "gas_cost_increase_multiplier": 1.2
            },
            "batch_proposer_config": {
              "max_chunk_num_per_batch": 15,
              "max_l1_commit_gas_per_batch": 5000000,
              "max_l1_commit_calldata_size_per_batch": 123740,
              "batch_timeout_sec": 720000,
              "gas_cost_increase_multiplier": 1.2
            }
          },
          "db_config": {
            "driver_name": "postgres",
            "dsn": "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable",
            "maxOpenNum": 50,
            "maxIdleNum": 20
          }
        }

  migrate-db:
    enabled: true
    data:
      migrate-db.json: |
        {
            "driver_name": "postgres",
            "dsn": "postgres://postgres:qwerty12345@postgresql:5432/scroll?sslmode=disable"
        }

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-stack
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s