name: renovate-config-validator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify Renovate Configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
      - name: Renovate
        uses: renovatebot/github-action@v40.1.6
        env:
          RENOVATE_REPOSITORIES: "scroll-tech/scroll-stack"
        with:
          token: "${{ secrets.RENOVATE_TOKEN }}"
