name: Build and publish docker image

on:
  push:
    tags:
      - 'scroll-alpine-*'
jobs:
  build:
    name: Clone, Build, Publish
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag version
        id: extract_tag
        run: |
          # Extract the tag version part from the ref name
          VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/^scroll-alpine-//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build image
        id: build
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: scroll-alpine
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: custom-images/scroll-alpine/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:latest

